name: Teste Self-Hosted Runner

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: [self-hosted, local, terraform, docker]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Mostrar infos da máquina
        run: |
          echo "Usuário:"
          whoami
          echo "Sistema:"
          uname -a
          echo "Docker:"
          docker --version
          echo "Go:"
          go version

      - name: Build da aplicação Go
        run: go build -v ./...

      - name: Build da imagem Docker
        run: docker build -t go-devops-app:test .

      - name: Teste do container
        run: |
          docker run -d -p 8080:8080 --name teste-go go-devops-app:test
          sleep 3
          curl http://localhost:8080/health
          docker rm -f teste-go
